import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { CircleHelp, Check, Download, Pencil, Plus, FileBarChart2, FileCheck2, Filter, MapPin, MessageCircle, Search, Send, ShieldAlert, ShieldCheck, Sparkles, TriangleAlert, Users, Bell, CheckCheck, ExternalLink, RefreshCw, Bot, Clock3, Database, Settings as SettingsIcon, LockKeyhole, Moon } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api, formatDate, humanize } from '../lib/api';
import { useAuth } from '../context/AuthContext';
import { useScope } from '../context/ScopeContext';
import { useToast } from '../context/ToastContext';
import { Modal } from '../components/Modal';
import { FormFields, type FieldConfig } from '../components/FormFields';
import type { Mine, RecordBase, User } from '../types';
import { Avatar, Button, Card, DataTable, EmptyState, LoadingState, PageHeader, RiskBadge, StatusBadge } from '../components/ui';

function useMineDirectory() { const [mines, setMines] = useState<Mine[]>([]); useEffect(() => { api.get<Mine[]>('/mines').then(setMines).catch(() => setMines([])); }, []); return mines; }
const recordLink = (type: string, id: string) => type === 'compliance' ? `/compliance/${id}` : type === 'violation' ? `/violations/${id}` : type === 'action' ? `/actions/${id}` : type === 'inspection' ? `/inspections/${id}` : `/mines/${id}`;

export function RiskAnalyticsPage() {
  const { selectedMine } = useScope(); const navigate = useNavigate(); const toast = useToast(); const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setRows(await api.get<any[]>(`/dashboard/risk${selectedMine !== 'all' ? `?mineId=${selectedMine}` : ''}`)); } catch (error) { toast(error instanceof Error ? error.message : 'Risk data could not be loaded.', 'error'); } finally { setLoading(false); } }, [selectedMine, toast]);
  useEffect(() => { void load(); }, [load]);
  const distribution = useMemo(() => ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map((level) => ({ level, count: rows.filter((item) => item.risk.level === level).length, color: ({ LOW: '#28a879', MEDIUM: '#e9b949', HIGH: '#ed8e42', CRITICAL: '#d94d58' } as Record<string, string>)[level] })), [rows]);
  const components = useMemo(() => [
    { factor: 'Severity', score: rows.length ? Math.round(rows.reduce((sum, item) => sum + item.risk.components.severity, 0) / rows.length) : 0 },
    { factor: 'Overdue', score: rows.length ? Math.round(rows.reduce((sum, item) => sum + item.risk.components.overdueDays, 0) / rows.length) : 0 },
    { factor: 'Repeated findings', score: rows.length ? Math.round(rows.reduce((sum, item) => sum + item.risk.components.repeatedViolations, 0) / rows.length) : 0 },
    { factor: 'Compliance gap', score: rows.length ? Math.round(rows.reduce((sum, item) => sum + item.risk.components.complianceGap, 0) / rows.length) : 0 },
    { factor: 'Unresolved actions', score: rows.length ? Math.round(rows.reduce((sum, item) => sum + item.risk.components.unresolvedActions, 0) / rows.length) : 0 },
  ], [rows]);
  return <div className="page-enter"><PageHeader eyebrow="INTELLIGENCE · EXPLAINABLE BY DESIGN" title="Risk analytics" description="A deterministic, transparent risk model highlights emerging pressure points—without relying on AI for official scores." actions={<Link className="btn btn-secondary" to="/reports"><FileBarChart2 size={15} /> Export a report</Link>} />
    <div className="risk-method-banner"><span className="risk-method-icon"><ShieldCheck size={18} /></span><div><b>Official mine risk is calculated by the backend risk engine</b><p>Severity 30% · overdue days 25% · repeat violations 20% · compliance gap 15% · unresolved actions 10%. Each factor is normalized to 0–100.</p></div><Link to="/ai-assistant">Ask AI to explain <Sparkles size={14} /></Link></div>
    {loading ? <LoadingState label="Calculating mine risk profiles…" /> : <>
      <div className="risk-analytics-top"><Card title="Portfolio risk distribution" subtitle="Current rating by monitored mine"><div className="analytics-donut-row"><div className="analytics-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} dataKey="count" nameKey="level" innerRadius="63%" outerRadius="90%" paddingAngle={4} stroke="none">{distribution.map((entry) => <Cell key={entry.level} fill={entry.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="donut-center"><strong>{rows.length}</strong><small>mines</small></div></div><div className="analytics-risk-legend">{distribution.map((entry) => <div key={entry.level}><span><i style={{ background: entry.color }} />{entry.level}</span><b>{entry.count}</b></div>)}</div></div></Card>
        <Card title="Portfolio factor pressure" subtitle="Average normalized risk factor across selected mines"><div className="risk-factor-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={components} margin={{ left: -22, right: 10, top: 10, bottom: 8 }}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="var(--chart-grid)" /><XAxis dataKey="factor" axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 10 }} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} tick={{ fill: 'var(--text-muted)', fontSize: 10 }} /><Tooltip contentStyle={{ border: '1px solid var(--border)', borderRadius: 12, background: 'var(--surface)', color: 'var(--text-main)', fontSize: 12 }} /><Bar dataKey="score" fill="#7188ee" radius={[5, 5, 0, 0]} barSize={32} /></BarChart></ResponsiveContainer></div></Card></div>
      <Card className="records-card" title="Mine risk register" subtitle="Ranked by the current deterministic risk score" noPadding><DataTable rows={rows} onRowClick={(mine) => navigate(`/mines/${mine.id}`)} columns={[
        { key: 'name', label: 'Mine', render: (mine) => <div className="mine-cell"><span className="mine-cell-icon"><MapPin size={15} /></span><span><b>{mine.name}</b><small>{mine.code} · {mine.district}</small></span></div> },
        { key: 'risk.score', label: 'Risk', render: (mine) => <div className="risk-score-cell"><strong>{mine.risk.score}</strong><div className="risk-meter"><i className={`risk-meter-${mine.risk.level.toLowerCase()}`} style={{ width: `${mine.risk.score}%` }} /></div><RiskBadge level={mine.risk.level} /></div> },
        { key: 'compliancePercentage', label: 'Compliance', render: (mine) => `${mine.compliancePercentage}%` },
        { key: 'openViolations', label: 'Open violations' }, { key: 'overdueActions', label: 'Overdue actions' },
        { key: 'factors', label: 'Primary factor', render: (mine) => <span className="risk-primary-factor">{mine.risk.factors?.[0] || 'No material open risk'}</span> },
      ]} emptyTitle="No mines in scope" /></Card>
    </>}
  </div>;
}

const reportTypes = [
  { id: 'compliance', title: 'Compliance report', description: 'Statutory requirements, deadlines, categories and evidence status.', icon: ShieldCheck, tone: 'green' },
  { id: 'inspection', title: 'Inspection report', description: 'Field observations, severity, inspectors and geospatial capture.', icon: FileCheck2, tone: 'blue' },
  { id: 'violation', title: 'Violation report', description: 'Open findings, assigned owners, severity and remediation deadlines.', icon: ShieldAlert, tone: 'rose' },
  { id: 'action', title: 'Corrective action report', description: 'Assignment, evidence submission and verification status.', icon: ClipboardCheckIcon, tone: 'violet' },
];
function ClipboardCheckIcon() { return <FileCheck2 size={18} />; }
function csvEscape(value: unknown) { const raw = value === null || value === undefined ? '' : typeof value === 'object' ? JSON.stringify(value) : String(value); const safe = typeof value === 'string' && /^[\t\r\n ]*[=+@-]/.test(raw) ? `'${raw}` : raw; return `"${safe.replaceAll('"', '""')}"`; }
export function ReportsPage() {
  const { selectedMine } = useScope(); const mines = useMineDirectory(); const toast = useToast();
  const [report, setReport] = useState('compliance'); const [rows, setRows] = useState<RecordBase[]>([]); const [loading, setLoading] = useState(false); const [mineId, setMineId] = useState(selectedMine); const [status, setStatus] = useState('all'); const [category, setCategory] = useState('all'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [generated, setGenerated] = useState<string | null>(null);
  useEffect(() => setMineId(selectedMine), [selectedMine]);
  const config = reportTypes.find((item) => item.id === report) || reportTypes[0];
  const run = useCallback(async () => { setLoading(true); try { const query = new URLSearchParams(); if (mineId !== 'all') query.set('mineId', mineId); if (status !== 'all') query.set('status', status); if (category !== 'all') query.set('category', category); if (from) query.set('from', from); if (to) query.set('to', to); const result = await api.get<{ rows: RecordBase[] }>(`/reports/${report}?${query.toString()}`); setRows(result.rows); setGenerated(new Date().toISOString()); } catch (error) { toast(error instanceof Error ? error.message : 'Report could not be generated.', 'error'); } finally { setLoading(false); } }, [report, mineId, status, category, from, to, toast]);
  useEffect(() => { void run(); }, [run]);
  const categories = report === 'compliance' || report === 'violation' ? ['Safety', 'Environment', 'Labour', 'Production', 'Documentation', 'Equipment'] : report === 'inspection' ? ['Safety', 'Environment', 'Labour', 'Production', 'Equipment', 'General'] : [];
  function exportCsv() {
    if (!rows.length) { toast('There are no report rows to export.', 'info'); return; }
    const keys = Object.keys(rows[0]).filter((key) => !['_id', 'passwordHash', '__v'].includes(key));
    const content = [keys.map(csvEscape).join(','), ...rows.map((row) => keys.map((key) => csvEscape((row as any)[key])).join(','))].join('\r\n');
    const blob = new Blob([`\uFEFF${content}`], { type: 'text/csv;charset=utf-8;' }); const href = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = href; anchor.download = `minegov-${report}-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(href); toast('CSV report downloaded.');
  }
  return <div className="page-enter"><PageHeader eyebrow="REPORTING & ASSURANCE" title="Reports" description="Create filtered, export-ready operational reports from live governance records." actions={<Button variant="secondary" onClick={exportCsv} disabled={!rows.length}><Download size={15} /> Export CSV</Button>} />
    <div className="report-type-grid">{reportTypes.map((item) => { const Icon = item.icon; return <button onClick={() => setReport(item.id)} key={item.id} className={`report-type-card ${report === item.id ? 'selected' : ''}`}><span className={`report-type-icon ${item.tone}`}><Icon size={18} /></span><span><b>{item.title}</b><small>{item.description}</small></span><span className="report-type-radio" /></button>; })}</div>
    <Card className="report-filter-card" title="Report filters" subtitle="Each export reflects the selected records and date range"><div className="report-filters"><label className="form-field"><span>Mine</span><select value={mineId} onChange={(event) => setMineId(event.target.value)}><option value="all">All accessible mines</option>{mines.map((mine) => <option key={mine.id} value={mine.id}>{mine.name}</option>)}</select></label><label className="form-field"><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{(report === 'compliance' ? ['COMPLIANT', 'PENDING', 'UNDER_REVIEW', 'OVERDUE'] : report === 'violation' ? ['OPEN', 'IN_PROGRESS', 'ACTION_SUBMITTED', 'VERIFICATION_PENDING', 'CLOSED', 'OVERDUE'] : report === 'action' ? ['OPEN', 'IN_PROGRESS', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'OVERDUE'] : ['SUBMITTED']).map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</select></label>{categories.length > 0 && <label className="form-field"><span>Category</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map((value) => <option key={value}>{value}</option>)}</select></label>}<label className="form-field"><span>From date</span><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="form-field"><span>To date</span><input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><Button className="generate-report-button" onClick={() => void run()} disabled={loading}><RefreshCw size={15} className={loading ? 'spin' : ''} /> Generate</Button></div></Card>
    <Card className="report-results-card" title={config.title} subtitle={generated ? `Generated ${formatDate(generated, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })} · Live application data` : 'Loading report'} action={<span className="report-count">{rows.length} records</span>} noPadding><div className="report-table-wrap">{loading ? <LoadingState label="Building report from live records…" /> : <DataTable rows={rows} columns={report === 'compliance' ? [{ key: 'title', label: 'Requirement', render: (item) => <b>{item.title}</b> }, { key: 'mineName', label: 'Mine' }, { key: 'category', label: 'Category' }, { key: 'assignedOfficer', label: 'Officer', render: (item) => item.officerName }, { key: 'dueDate', label: 'Due date', render: (item) => formatDate(item.dueDate) }, { key: 'status', label: 'Status', render: (item) => <StatusBadge value={item.status} /> }] : report === 'inspection' ? [{ key: 'observation', label: 'Observation', render: (item) => <b>{item.observation}</b> }, { key: 'mineName', label: 'Mine' }, { key: 'inspectionType', label: 'Type' }, { key: 'date', label: 'Date', render: (item) => formatDate(item.date) }, { key: 'severity', label: 'Severity', render: (item) => <StatusBadge value={item.severity} /> }] : report === 'violation' ? [{ key: 'title', label: 'Violation', render: (item) => <b>{item.title}</b> }, { key: 'mineName', label: 'Mine' }, { key: 'category', label: 'Category' }, { key: 'severity', label: 'Severity', render: (item) => <StatusBadge value={item.severity} /> }, { key: 'deadline', label: 'Deadline', render: (item) => formatDate(item.deadline) }, { key: 'status', label: 'Status', render: (item) => <StatusBadge value={item.status} /> }] : [{ key: 'description', label: 'Corrective action', render: (item) => <b>{item.description}</b> }, { key: 'mineName', label: 'Mine' }, { key: 'officerName', label: 'Assigned officer' }, { key: 'deadline', label: 'Deadline', render: (item) => formatDate(item.deadline) }, { key: 'status', label: 'Status', render: (item) => <StatusBadge value={item.status} /> }]} emptyTitle="No records for these filters" emptyDescription="Adjust your date range or select a different report type." />}</div></Card>
  </div>;
}

type ChatMessage = { id: number; role: 'assistant' | 'user'; content: string; provider?: string; sources?: { label: string; type: string; href: string }[] };
const suggestions = ['Which compliances are overdue?', 'Show high-risk mines.', 'What are the major risks in Wardha Open Cast Mine?', 'Which officers have pending actions?', 'Show repeated safety violations.', 'Generate a monthly compliance summary.'];
export function AIAssistantPage() {
  const toast = useToast(); const [messages, setMessages] = useState<ChatMessage[]>([{ id: 1, role: 'assistant', content: 'Hello. I’m your MineGov intelligence assistant. I can summarize live mine, compliance, inspection, violation and corrective-action records. Official risk scores always come from the deterministic risk engine—not AI.' }]);
  const [question, setQuestion] = useState(''); const [busy, setBusy] = useState(false);
  async function ask(text = question) {
    const value = text.trim(); if (!value || busy) return;
    const userMessage: ChatMessage = { id: Date.now(), role: 'user', content: value }; setMessages((items) => [...items, userMessage]); setQuestion(''); setBusy(true);
    try { const result = await api.post<{ answer: string; provider: string; sources: ChatMessage['sources'] }>('/ai/chat', { question: value }); setMessages((items) => [...items, { id: Date.now() + 1, role: 'assistant', content: result.answer, provider: result.provider, sources: result.sources }]); }
    catch (error) { const message = error instanceof Error ? error.message : 'AI assistant is unavailable.'; toast(message, 'error'); setMessages((items) => [...items, { id: Date.now() + 1, role: 'assistant', content: `I couldn't complete that request: ${message}` }]); }
    finally { setBusy(false); }
  }
  return <div className="page-enter ai-page"><PageHeader eyebrow="MINEGOV INTELLIGENCE" title="AI assistant" description="Ask questions about your operational data. Every response is grounded in application records." actions={<span className="ai-availability"><span className="live-dot" /> Database connected · deterministic fallback ready</span>} />
    <div className="ai-workspace"><div className="ai-chat-panel"><div className="ai-chat-header"><div className="ai-avatar"><Sparkles size={17} /></div><div><b>MineGov Assistant</b><small><span className="live-dot" /> Available · data-grounded</small></div><span className="ai-safety-chip"><ShieldCheck size={13} /> Grounded answers</span></div>
      <div className="chat-scroll">{messages.map((message) => <div className={`chat-message-row ${message.role}`} key={message.id}><div className={`chat-avatar ${message.role}`}>{message.role === 'assistant' ? <Bot size={16} /> : <Avatar name="You" size="sm" />}</div><div className="chat-message"><div className="chat-message-meta">{message.role === 'assistant' ? 'MINEGOV AI' : 'YOU'} {message.provider && <span>· {message.provider}</span>}</div><p>{message.content}</p>{message.sources?.length ? <div className="chat-sources"><small>Referenced data</small>{message.sources.map((source) => <Link key={`${source.type}-${source.href}`} to={source.href}><span>{source.type}</span>{source.label}<ExternalLink size={12} /></Link>)}</div> : null}</div></div>)}{busy && <div className="chat-message-row assistant"><div className="chat-avatar assistant"><Bot size={16} /></div><div className="chat-message"><div className="chat-message-meta">MINEGOV AI</div><div className="typing-indicator"><i /><i /><i /></div><small>Reviewing application records…</small></div></div>}</div>
      <form className="chat-composer" onSubmit={(event) => { event.preventDefault(); void ask(); }}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about your mines, compliance or risk…" maxLength={1000} disabled={busy} /><span className="composer-hint">Answers use live MineGov data</span><Button type="submit" disabled={!question.trim() || busy} aria-label="Send message"><Send size={16} /></Button></form>
    </div><aside className="ai-side-panel"><Card title="Try asking" subtitle="Suggested questions grounded in your data"><div className="suggested-questions">{suggestions.map((text) => <button key={text} onClick={() => void ask(text)} disabled={busy}><span><MessageCircle size={14} /></span>{text}<ExternalLink size={12} /></button>)}</div></Card><div className="ai-integrity-card"><div className="integrity-icon"><ShieldCheck size={18} /></div><b>Built for trustworthy governance</b><p>AI can summarize records, but cannot change risk scores or invent database facts. With no API key, a deterministic assistant answers from live records.</p><div><CheckCircle2Small /> Official risk engine is separate</div><div><CheckCircle2Small /> AI provider is optional</div><div><CheckCircle2Small /> Questions are grounded in mine data</div></div><div className="ai-provider-note"><Sparkles size={14} /> Add AI_PROVIDER and AI_API_KEY on the server to enable Gemini or OpenAI-compatible responses.</div></aside></div>
  </div>;
}
function CheckCircle2Small() { return <ShieldCheck size={13} />; }

export function NotificationsPage() {
  const { selectedMine } = useScope(); const toast = useToast(); const [alerts, setAlerts] = useState<RecordBase[]>([]); const [loading, setLoading] = useState(true); const [unreadOnly, setUnreadOnly] = useState(false); const [severity, setSeverity] = useState('all');
  const load = useCallback(async () => { setLoading(true); try { const query = new URLSearchParams(); if (selectedMine !== 'all') query.set('mineId', selectedMine); if (unreadOnly) query.set('read', 'false'); if (severity !== 'all') query.set('severity', severity); setAlerts(await api.get<RecordBase[]>(`/alerts?${query.toString()}`)); } catch (error) { toast(error instanceof Error ? error.message : 'Notifications could not be loaded.', 'error'); } finally { setLoading(false); } }, [selectedMine, unreadOnly, severity, toast]);
  useEffect(() => { void load(); }, [load]);
  async function markRead(id: string) { try { await api.put(`/alerts/${id}/read`, {}); setAlerts((items) => items.map((item) => item.id === id ? { ...item, read: true } : item)); window.dispatchEvent(new Event('minegov:meta-changed')); } catch (error) { toast(error instanceof Error ? error.message : 'Alert could not be updated.', 'error'); } }
  async function markAll() { try { await api.put('/alerts/read-all', {}); setAlerts((items) => items.map((item) => ({ ...item, read: true }))); window.dispatchEvent(new Event('minegov:meta-changed')); toast('All notifications marked as read.'); } catch (error) { toast(error instanceof Error ? error.message : 'Alerts could not be updated.', 'error'); } }
  const unreadCount = alerts.filter((item) => !item.read).length;
  return <div className="page-enter"><PageHeader eyebrow="SYSTEM ALERTS" title="Notifications" description="Automated compliance, deadline, violation and risk signals across your operational scope." actions={<Button variant="secondary" onClick={markAll} disabled={!unreadCount}><CheckCheck size={15} /> Mark all read</Button>} />
    <div className="notification-controls"><button className={`filter-toggle ${unreadOnly ? 'active' : ''}`} onClick={() => setUnreadOnly((value) => !value)}><span className="filter-toggle-dot" /> Unread only</button><label className="filter-select"><Filter size={14} /><select value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="all">All severities</option>{['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((value) => <option key={value}>{value}</option>)}</select></label><span className="notification-count"><b>{unreadCount}</b> unread of {alerts.length}</span></div>
    <Card className="notifications-card" noPadding>{loading ? <LoadingState label="Checking alert feed…" /> : alerts.length ? <div className="notification-list">{alerts.map((alert) => <div className={`notification-row ${alert.read ? 'is-read' : ''}`} key={alert.id}><span className={`notification-icon notification-${alert.severity?.toLowerCase()}`}>{alert.severity === 'CRITICAL' ? <TriangleAlert size={17} /> : alert.type?.includes('COMPLIANCE') ? <ShieldCheck size={17} /> : alert.type?.includes('MINE') ? <HardHatIcon /> : <ShieldAlert size={17} />}</span><div className="notification-copy"><div className="notification-overline">{humanize(alert.type)} <i>·</i> {formatDate(alert.createdAt, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</div><b>{alert.message}</b><small>{alert.mineName || 'Mine alert'} · <StatusBadge value={alert.severity} size="sm" /></small></div><div className="notification-row-actions">{!alert.read && <button onClick={() => void markRead(alert.id)} title="Mark as read"><Check size={15} /></button>}<Link to={recordLink(alert.entityType || 'mine', alert.entityType === 'mine' && String(alert.entityId || '').includes(':') ? alert.mineId : (alert.entityId || alert.mineId))} title="Open related record"><ArrowRightSmall /></Link></div></div>)}</div> : <EmptyState title="You're all caught up" description="No alerts match the selected filters." />}</Card>
  </div>;
}
function HardHatIcon() { return <MapPin size={17} />; }
function ArrowRightSmall() { return <ExternalLink size={15} />; }

export function AuditLogsPage() {
  const toast = useToast(); const [logs, setLogs] = useState<RecordBase[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [entity, setEntity] = useState('all');
  useEffect(() => { api.get<RecordBase[]>('/audit-logs').then(setLogs).catch((error) => toast(error instanceof Error ? error.message : 'Audit log access is unavailable.', 'error')).finally(() => setLoading(false)); }, [toast]);
  const filtered = logs.filter((log) => (entity === 'all' || log.entity === entity) && (!query || `${log.userName} ${log.action} ${log.entity}`.toLowerCase().includes(query.toLowerCase())));
  return <div className="page-enter"><PageHeader eyebrow="ADMINISTRATION · IMMUTABLE ACTIVITY" title="Audit logs" description="Review who changed what and when across important governance actions." actions={<span className="audit-retention"><LockKeyhole size={14} /> Admin-only access</span>} />
    <div className="audit-trust-strip"><span><Database size={16} /> {logs.length} recorded events</span><i /><span><Users size={16} /> User-attributed changes</span><i /><span><Clock3 size={16} /> Timestamped activity trail</span></div>
    <Card className="records-card" noPadding><div className="table-toolbar"><label className="table-search"><Search size={16} /><input placeholder="Search actions or users…" value={query} onChange={(event) => setQuery(event.target.value)} /></label><label className="filter-select"><Filter size={14} /><select value={entity} onChange={(event) => setEntity(event.target.value)}><option value="all">All entities</option>{['Mine', 'Compliance', 'Inspection', 'Violation', 'CorrectiveAction', 'Alert', 'User'].map((value) => <option key={value}>{value}</option>)}</select></label></div>
      <DataTable rows={filtered} loading={loading} columns={[{ key: 'action', label: 'Activity', render: (log) => <div className="primary-cell"><b>{log.action}</b><small>{log.entity} · {String(log.entityId || '').slice(-8)}</small></div> }, { key: 'userName', label: 'Performed by', render: (log) => <span className="audit-user"><Avatar name={log.userName} size="sm" />{log.userName}</span> }, { key: 'createdAt', label: 'Date & time', render: (log) => <span className="two-line"><b>{formatDate(log.createdAt, { month: 'short', day: 'numeric', year: 'numeric' })}</b><small>{formatDate(log.createdAt, { hour: 'numeric', minute: '2-digit', second: '2-digit' })}</small></span> }, { key: 'ipAddress', label: 'Source', render: (log) => <span className="cell-muted">{log.ipAddress || 'Application'}</span> }, { key: 'diff', label: 'Change details', render: (log) => <details className="audit-details"><summary>Inspect</summary><pre>{JSON.stringify({ oldValue: log.oldValue, newValue: log.newValue }, null, 2)}</pre></details> }]} emptyTitle="No audit events found" emptyDescription="Important changes will be recorded here." />
    </Card></div>;
}

export function SettingsPage() {
  const { user } = useAuth(); const [theme, setTheme] = useState(() => localStorage.getItem('minegov_theme') || 'light'); const toast = useToast();
  const [users, setUsers] = useState<User[]>([]); const [mines, setMines] = useState<Mine[]>([]); const [userModal, setUserModal] = useState(false); const [editingUser, setEditingUser] = useState<User | null>(null); const [userValues, setUserValues] = useState<Record<string, any>>({}); const [userBusy, setUserBusy] = useState(false);
  const isAdmin = user?.role === 'ADMIN';
  const loadUsers = useCallback(async () => { if (!isAdmin) return; try { const [directory, mineDirectory] = await Promise.all([api.get<User[]>('/users'), api.get<Mine[]>('/mines')]); setUsers(directory); setMines(mineDirectory); } catch (error) { toast(error instanceof Error ? error.message : 'User directory could not be loaded.', 'error'); } }, [isAdmin, toast]);
  useEffect(() => { void loadUsers(); }, [loadUsers]);
  const userFields: FieldConfig[] = [
    { name: 'name', label: 'Full name', required: true },
    ...(editingUser ? [] : [{ name: 'email', label: 'Email address', type: 'email' as const, required: true }]),
    { name: 'role', label: 'Role', type: 'select', required: true, options: ['ADMIN', 'MINE_OFFICER', 'INSPECTOR', 'MANAGEMENT'].map((value) => ({ label: humanize(value), value })) },
    { name: 'mineId', label: 'Assigned mine', type: 'select', options: [{ label: 'Portfolio-wide / none', value: '' }, ...mines.map((mine) => ({ label: mine.name, value: mine.id }))] },
    { name: 'department', label: 'Department' },
    ...(editingUser ? [{ name: 'newPassword', label: 'Reset password (optional)', type: 'password' as const, placeholder: 'Leave blank to keep current password', hint: '10–72 characters when changing.' }] : [{ name: 'password', label: 'Initial password', type: 'password' as const, required: true, hint: '10–72 characters.' }]),
    ...(editingUser ? [{ name: 'active', label: 'Account status', type: 'select' as const, options: [{ label: 'Active', value: 'true' }, { label: 'Disabled', value: 'false' }] }] : []),
  ];
  const openUser = (account?: User) => { setEditingUser(account || null); setUserValues(account ? { ...account, active: account.active === false ? 'false' : 'true', mineId: account.mineId || '' } : { name: '', email: '', role: 'INSPECTOR', mineId: '', department: '', password: '' }); setUserModal(true); };
  async function saveUser(event: FormEvent) { event.preventDefault(); setUserBusy(true); try { const payload = { ...userValues }; if (editingUser) { payload.active = payload.active === 'true'; if (!payload.newPassword) delete payload.newPassword; await api.put(`/users/${editingUser.id}`, payload); } else { await api.post('/users', payload); } toast(editingUser ? 'User access updated.' : 'User account created.'); setUserModal(false); await loadUsers(); } catch (error) { toast(error instanceof Error ? error.message : 'User could not be saved.', 'error'); } finally { setUserBusy(false); } }
  async function toggleUser(account: User) { try { await api.put(`/users/${account.id}`, { active: account.active === false }); toast(account.active === false ? 'User account enabled.' : 'User account disabled.'); await loadUsers(); } catch (error) { toast(error instanceof Error ? error.message : 'User access could not be changed.', 'error'); } }
  function changeTheme(value: string) { setTheme(value); document.documentElement.dataset.theme = value; localStorage.setItem('minegov_theme', value); window.dispatchEvent(new CustomEvent('minegov:theme-change', { detail: value })); toast(`${value === 'dark' ? 'Dark' : 'Light'} theme enabled.`); }
  const demoAccounts = [{ email: 'admin@example.com', role: 'Administrator' }, { email: 'officer@example.com', role: 'Mine officer' }, { email: 'inspector@example.com', role: 'Inspector' }, { email: 'manager@example.com', role: 'Management' }];
  return <div className="page-enter"><PageHeader eyebrow="PREFERENCES & ACCESS" title="Settings" description="Your MineGov profile, display preferences and development demo access." />
    <div className="settings-layout"><div className="settings-main"><Card title="Your account" subtitle="Identity and access profile"><div className="settings-profile"><Avatar name={user?.name} size="lg" color="blue" /><div><b>{user?.name}</b><span>{user?.email}</span><StatusBadge value={humanize(user?.role)} /></div></div><div className="detail-field-grid settings-account-details"><DetailField label="Role" value={humanize(user?.role)} /><DetailField label="Department" value={user?.department} /><DetailField label="Mine assignment" value={user?.mineId ? 'Assigned mine' : 'Portfolio-wide'} /></div></Card>
      <Card title="Appearance" subtitle="Choose a display theme for this device"><div className="theme-choice-row"><div><span className="theme-choice-icon"><Moon size={17} /></span><span><b>Interface theme</b><small>Saved locally in this browser</small></span></div><div className="theme-segment"><button className={theme === 'light' ? 'active' : ''} onClick={() => changeTheme('light')}>Light</button><button className={theme === 'dark' ? 'active' : ''} onClick={() => changeTheme('dark')}>Dark</button></div></div></Card>
      {isAdmin && <Card className="records-card user-management-card" title="User access management" subtitle="Manage portfolio accounts, role scopes and mine assignments" action={<Button size="sm" onClick={() => openUser()}><Plus size={14} /> Add user</Button>} noPadding><DataTable<User> rows={users} columns={[{ key: 'name', label: 'User', render: (account) => <div className="audit-user"><Avatar name={account.name} size="sm" /><span className="two-line"><b>{account.name}</b><small>{account.email}</small></span></div> }, { key: 'role', label: 'Role', render: (account) => <StatusBadge value={humanize(account.role)} /> }, { key: 'mineId', label: 'Assignment', render: (account) => mines.find((mine) => mine.id === account.mineId)?.name || 'Portfolio-wide' }, { key: 'active', label: 'Access', render: (account) => <StatusBadge value={account.active === false ? 'INACTIVE' : 'ACTIVE'} /> }, { key: 'actions', label: '', render: (account) => <div className="user-table-actions"><button className="icon-button table-action" title="Edit user" onClick={() => openUser(account)}><Pencil size={14} /></button>{account.id !== user?.id && <button className="user-toggle" onClick={() => void toggleUser(account)}>{account.active === false ? 'Enable' : 'Disable'}</button>}</div> }]} emptyTitle="No users found" emptyDescription="Create a user to grant access to MineGov." />
        <Modal open={userModal} onClose={() => setUserModal(false)} title={editingUser ? 'Edit user access' : 'Create user account'} description="Set the user's role, mine assignment and secure credentials." onSubmit={saveUser} submitLabel={editingUser ? 'Save access' : 'Create user'} busy={userBusy} wide><FormFields fields={userFields} values={userValues} onChange={(name, value) => setUserValues((current) => ({ ...current, [name]: value }))} /></Modal></Card>}</div>
      <aside className="settings-aside">{import.meta.env.DEV ? <div className="demo-credentials-card"><div className="demo-credentials-icon"><SettingsIcon size={17} /></div><span className="eyebrow">DEVELOPMENT ONLY</span><h3>Demo access</h3><p>Sample accounts are for local evaluation only. Change credentials before any public deployment.</p><div className="demo-password">Shared password <b>MineGov2026!</b></div>{demoAccounts.map((account) => <div className="demo-account" key={account.email}><span><b>{account.email}</b><small>{account.role}</small></span><button onClick={() => { navigator.clipboard?.writeText(account.email); toast('Demo email copied.'); }}>Copy</button></div>)}<div className="demo-note"><LockKeyhole size={13} /> Passwords are hashed in the backend.</div></div> : <div className="demo-credentials-card"><div className="demo-credentials-icon"><LockKeyhole size={17} /></div><span className="eyebrow">ACCESS SECURITY</span><h3>Role-based access</h3><p>Your account uses a 12-hour signed session. User roles scope mine visibility and workflow permissions.</p></div>}</aside></div>
    </div>;
}
function DetailField({ label, value }: { label: string; value?: string }) { return <div className="detail-field"><small>{label}</small><b>{value || '—'}</b></div>; }

export function SearchPage() {
  const [params, setParams] = useSearchParams(); const [query, setQuery] = useState(params.get('q') || ''); const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(false); const toast = useToast();
  useEffect(() => { const value = params.get('q') || ''; setQuery(value); if (!value) return; setLoading(true); api.get<any[]>(`/search?q=${encodeURIComponent(value)}`).then(setRows).catch((error) => toast(error instanceof Error ? error.message : 'Search failed.', 'error')).finally(() => setLoading(false)); }, [params, toast]);
  function submit(event: FormEvent) { event.preventDefault(); setParams({ q: query }); }
  return <div className="page-enter"><PageHeader eyebrow="GLOBAL SEARCH" title="Search MineGov" description="Find mines, statutory requirements, inspection observations, violations and actions." />
    <form className="search-page-form" onSubmit={submit}><Search size={18} /><input autoFocus placeholder="Try a mine name, regulation or finding…" value={query} onChange={(event) => setQuery(event.target.value)} /><Button type="submit">Search</Button></form>
    <div className="search-results-heading"><h2>{params.get('q') ? `Results for “${params.get('q')}”` : 'Search records'}</h2>{!loading && <span>{rows.length} matching records</span>}</div>
    {loading ? <LoadingState label="Searching accessible records…" /> : rows.length ? <div className="search-result-list">{rows.map((row) => <Link to={row.href} className="search-result" key={`${row.type}-${row.id}`}><span className="search-result-icon"><Search size={16} /></span><span><b>{row.title}</b><small>{row.subtitle}</small></span><StatusBadge value={row.type} size="sm" /><ExternalLink size={14} /></Link>)}</div> : params.get('q') ? <EmptyState title="No matching records" description="Check the spelling or search for a different mine, finding or category." /> : <EmptyState title="Search across your portfolio" description="Use the search box above to find accessible MineGov records." />}
  </div>;
}

export function NotFoundPage() { return <div className="not-found"><div className="not-found-code">404</div><h1>Page not found</h1><p>The page you’re looking for may have moved or is not available in this demo.</p><Link className="btn btn-primary" to="/dashboard">Return to dashboard</Link></div>; }
